#The version. Do not touch this.
version: 1.5.0
#The incoming webhook URL you got from Slack.
webhook: https://hooks.slack.com/services/
#The outgoing webhook token you got from Slack.
token:
#Show HTTP response codes in console
debug: false
#Send player commands to Slack
send-commands: false
#Causes a bit of lag but you can have certain players not post to Slack
use-perms: false
#Causes lag but you can block commands from being shown to Slack
use-blacklist: false
#Commands that will not show up in Slack when they are executed.
blacklist:
    - /login
    - /register
#incoming-webhook
incoming-webhook:
  enable: false
  bindaddress: 0.0.0.0
  port: 25560
  max-connections: 30
  token: ""
  msgformat: "&color;f<&color;5(Slack) &color;f%username%> %message%"
  # msgprefix: "&color;5[Slack]"
  # msgsuffix: "&color;f"
